# Пример
# https://github.com/MorkovkAs/openapi-example-toys/blob/main/.insomnia/ApiSpec/spc_b48e4d826bc849f5a3cf324b45d147d0.yml
openapi: 3.0.0
info:
  title:  Rest Api ZVK
  description: Homework 1 - system design Balun's courses.
  version: "v0.0.1"
tags:
  - name: friends
    description: Everything about your friends
  - name: feeds
    description: Everything about your feeds
  - name: user
    description: Operations about user
servers:
  - url: https://localhost/api/v1
    description: local server
paths:
  /friends{user_id}:
    get:
      tags:
        - friends
      summary: List of friends of current user
      parameters:
        - name: user_id
          in: path
          description: ID of user ID to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 200 response
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/friend"
        '404':
          description: User ID not found
        '500':
          description: Internal server error
  /friends:
    post:
      tags:
        - friends
      summary: Add friend
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/friend"
      responses:
        '200':
          description: OK
        '400':
          description: Incorrect data
        '500':
          description: Internal server error
    delete:
      summary: Delete friend
      tags:
        - friends
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 12
                friend_id:
                  type: integer
                  example: 28
      responses:
        '200':
          description: Успешное удаление
          content: { }
  /user{user_id}:
    get:
      tags:
        - user
      summary: Show user info
      parameters:
        - name: user_id
          in: path
          description: ID of user ID to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 200 response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/user"

        '404':
          description: User ID not found
        '500':
          description: Internal server error

  /feeds:
    post:
      tags:
        - feeds
      summary: Add feed
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/feed"
      responses:
        '200':
          description: OK
        '400':
          description: Incorrect data
        '500':
          description: Internal server error



components:
  schemas:
    friend:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 12
        username:
          type: string
          example: Kolya
        age:
          type: integer
          format: int64
          example: 21
    feed:
      type: object
      properties:
        feed_id:
          type: integer
          example: 77
        user_id:
          type: integer
          example: 64
        title:
          type: string
          example: "It's very important post about Doctor House"
    user:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 12
        username:
          type: string
          example: Kolya
        age:
          type: integer
          format: int64
          example: 21
        picture_url:
          type: string
          example: /proto.jpg
        feeds:
          type: array
          items:
            $ref: "#/components/schemas/feed"